Enable App Store publishing

diff --git a/codemagic.yaml b/codemagic.yaml
--- a/codemagic.yaml
+++ b/codemagic.yaml
@@ -14,14 +14,16 @@ workflows:
       - name: Set iOS deployment target
         script: | 
           #!/bin/sh
-          # ... (this script remains the same)
-          set -e; set -x;
+          set -e
+          set -x
           PODFILE_PATH=$(find ios -name Podfile)
           if [ -f "$PODFILE_PATH" ]; then
             sed -i.bak "2i\\
             platform :ios, '13.0'
             " "$PODFILE_PATH"
+            echo "Podfile successfully modified."
           else
+            echo "Podfile not found, attempting to set via .xcconfig"
             echo "IPHONEOS_DEPLOYMENT_TARGET = 13.0" >> ios/Flutter/Debug.xcconfig
             echo "IPHONEOS_DEPLOYMENT_TARGET = 13.0" >> ios/Flutter/Release.xcconfig
           fi
@@ -29,21 +31,9 @@ workflows:
         script: flutter packages pub get
       - name: Set Bundle ID in Xcode project
         script: /usr/libexec/PlistBuddy -c "Set :CFBundleIdentifier $BUNDLE_ID" "ios/Runner/Info.plist"
-      - name: Create App Store export options
-        script: | 
-          cat > /tmp/ExportOptions.plist << EOL
-          <?xml version="1.0" encoding="UTF-8"?>
-          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
-          <plist version="1.0">
-          <dict>
-            <key>method</key>
-            <string>app-store</string>
-            <key>signingStyle</key>
-            <string>automatic</string>
-          </dict>
-          </plist>
-          EOL
+      - name: Set up code signing for Development
+        script: xcode-project use-profiles --profile-type=DEVELOPMENT
       - name: Build iOS App
-        script: flutter build ipa --release --export-options-plist=/tmp/ExportOptions.plist
+        script: flutter build ipa --release
     artifacts:
       - build/ios/ipa/*.ipa
